name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:   
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Assemble
        run: ./gradlew assemble
      - name: Check
        run: ./gradlew check
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thomasfaure05/tp-devops
          tag_with_ref: true
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432:  
